# Generated by Django 5.2.4 on 2025-07-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=554)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('stream_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_rtsp_enabled', models.BooleanField(default=True)),
                ('server_rtmp_enabled', models.BooleanField(default=False)),
                ('log_level', models.CharField(default='info', max_length=10)),
            ],
        ),
    ]
