# Generated by Django 5.2.4 on 2025-07-22 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('detection', 'Object Detection'), ('recognition', 'Face Recognition'), ('behavior', 'Behavior Analysis'), ('vehicle', 'Vehicle Detection'), ('crowd', 'Crowd Analysis')], max_length=50)),
                ('accuracy', models.FloatField()),
                ('performance', models.IntegerField()),
                ('compatibility', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('motion', 'Motion Detection'), ('person', 'Person Detection'), ('vehicle', 'Vehicle Detection'), ('object', 'Object Detection')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('backup', 'Backup'), ('cloud', 'Cloud')], max_length=50)),
                ('total_space', models.FloatField()),
                ('used_space', models.FloatField()),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtsp_url', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('live', 'Live'), ('offline', 'Offline')], default='live', max_length=20)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='host',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='password',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='port',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='stream_path',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='username',
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='camera',
            name='fps',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='camera',
            name='motion_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='recording',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(default='1920x1080', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.CharField(default='Zone A', max_length=50),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='cameras',
            field=models.ManyToManyField(related_name='ai_models', to='monitoring.camera'),
        ),
        migrations.AddField(
            model_name='alert',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera'),
        ),
        migrations.AddField(
            model_name='stream',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera'),
        ),
    ]
