# Generated by Django 5.2.4 on 2025-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_aimodel_alert_storage_stream_supportticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='fps',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='motion_detection',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='status',
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='zone',
            field=models.CharField(max_length=100),
        ),
    ]
