# Generated by Django 5.2.4 on 2025-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_camera_fps_remove_camera_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, default='rtsp://placeholder', max_length=500),
        ),
    ]
